# Computer Science Engineer

### Education
BE, Computer Science engineering 

### Work Experience
Frontend Developer @ HashtoColon Systems Private Limited · Internship
->From Sep 2021 To Oct 2021 · 2 months
->Bengaluru South, Karnataka, India · HybridBengaluru South, Karnataka, India · Hybrid
->Skills: HTML · HTML5 · Cascading Style Sheets (CSS) · Bootstrap · JavaScript

### Projects
College recommendation system based on rank of the student

### Contact
email:joeldmello1998@gmail.com
